In [1]:
import pandas as pd
import numpy as np

## Series

In [2]:
s = pd.Series([34, 67, 10, True, 'Pune'])

In [3]:
s

0      34
1      67
2      10
3    True
4    Pune
dtype: object

In [4]:
type(s)

pandas.Series

In [5]:
s.size

5

In [6]:
s.shape

(5,)

In [7]:
s[4]

'Pune'

In [8]:
s[1: 3]

1    67
2    10
dtype: object

In [9]:
s = pd.Series([23, 56, 12, 10, 78], index = range(100, 105))

In [10]:
s

100    23
101    56
102    12
103    10
104    78
dtype: int64

In [11]:
s[101]

np.int64(56)

## Dataframe

In [12]:
roll = pd.Series([1, 2, 3, 4, 5])
cls = pd.Series(['te', 'be', 'be', 'se', 'te'])
marks = pd.Series([56, 76, 78, 39, 92])

In [13]:
df = pd.DataFrame({
    'id': roll,
    'class': cls,
    'marks': marks
})

In [14]:
df

   id class  marks
0   1    te     56
1   2    be     76
2   3    be     78
3   4    se     39
4   5    te     92

In [15]:
df.size

15

In [16]:
df.shape

(5, 3)

In [17]:
type(df)

pandas.DataFrame

In [18]:
df.columns

Index(['id', 'class', 'marks'], dtype='str')

In [19]:
pd.__version__

'3.0.3'

In [20]:
"""  
url -> https://mitu.co.in/dataset

this will open a drive folder
download all the files whose name is starting from student* -> eg... student.csv, student1.csv, ...
put the downloaded files in the same file folder as the current ipynb file

""";

In [21]:
pwd

'/home/aditya/MITU_SEP_2026/DS_Basics'

In [22]:
df = pd.read_csv('student.csv')

In [23]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [24]:
df.shape

(10, 5)

In [25]:
df.size

50

In [26]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='str')

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     str
 2   class   10 non-null     str
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 601.0 bytes

In [28]:
# try to load -> student1.csv, student3.tsv

In [29]:
df1 = pd.read_csv('student1.csv')
df1

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [30]:
headers = ['roll', 'name', 'class', 'marks', 'age']

In [31]:
df1 = pd.read_csv('student1.csv', names = headers)
df1

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [32]:
df1 = pd.read_csv('student3.tsv', sep = '\t')

In [33]:
df1

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [34]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     str
 2   class   10 non-null     str
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 601.0 bytes

In [36]:
df.describe()

           roll      marks        age
count  10.00000  10.000000  10.000000
mean    5.50000  64.499000  20.500000
std     3.02765   9.207179   1.269296
min     1.00000  49.550000  19.000000
25%     3.25000  57.520000  20.000000
50%     5.50000  64.310000  20.000000
75%     7.75000  69.327500  21.000000
max    10.00000  78.660000  23.000000

In [37]:
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [38]:
df.T

,0,1,2,3,4,5,6,7,8,9
roll,1,2,3,4,5,6,7,8,9,10
name,anil,amit,aniket,ajinkya,asha,ayesha,amar,amita,amol,anmol
class,TE,TE,BE,TE,TE,BE,BE,BE,TE,BE
marks,56.77,59.77,76.88,69.66,63.28,49.55,65.34,68.33,56.75,78.66
age,22,21,19,20,20,20,19,23,20,21

In [39]:
df.dtypes

roll       int64
name         str
class        str
marks    float64
age        int64
dtype: object

In [40]:
df.head()

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [41]:
df.head(7)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19

In [42]:
df.tail()

   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [43]:
df.tail(3)

   roll   name class  marks  age
7     8  amita    BE  68.33   23
8     9   amol    TE  56.75   20
9    10  anmol    BE  78.66   21

In [44]:
df.sum()

roll                                                    55
name     anilamitaniketajinkyaashaayeshaamaramitaamolanmol
class                                 TETEBETETEBEBEBETEBE
marks                                               644.99
age                                                    205
dtype: object

In [45]:
df.count()

roll     10
name     10
class    10
marks    10
age      10
dtype: int64

#### slicing

In [46]:
df.ndim

2

In [47]:
# iloc

In [48]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [49]:
df.iloc[0:5, 0: 4]

   roll     name class  marks
0     1     anil    TE  56.77
1     2     amit    TE  59.77
2     3   aniket    BE  76.88
3     4  ajinkya    TE  69.66
4     5     asha    TE  63.28

In [50]:
df.iloc[[0, 1, 2, 3, 4, 7, 8, 9], 0:3]

   roll     name class
0     1     anil    TE
1     2     amit    TE
2     3   aniket    BE
3     4  ajinkya    TE
4     5     asha    TE
7     8    amita    BE
8     9     amol    TE
9    10    anmol    BE

In [51]:
df.loc[0:5, 'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
Name: name, dtype: str

In [52]:
df.loc[0:5, ['name', 'class']]

      name class
0     anil    TE
1     amit    TE
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5   ayesha    BE

In [53]:
df.loc[:, 'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: str

In [54]:
df['name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: str

In [55]:
df[['name', 'class']]

      name class
0     anil    TE
1     amit    TE
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5   ayesha    BE
6     amar    BE
7    amita    BE
8     amol    TE
9    anmol    BE

In [56]:
df.name

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: str

In [57]:
# delete the column

In [58]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [59]:
df.drop(4)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [60]:
df.drop([3, 5, 6])

   roll    name class  marks  age
0     1    anil    TE  56.77   22
1     2    amit    TE  59.77   21
2     3  aniket    BE  76.88   19
4     5    asha    TE  63.28   20
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [61]:
df.drop(columns= ['class'])

   roll     name  marks  age
0     1     anil  56.77   22
1     2     amit  59.77   21
2     3   aniket  76.88   19
3     4  ajinkya  69.66   20
4     5     asha  63.28   20
5     6   ayesha  49.55   20
6     7     amar  65.34   19
7     8    amita  68.33   23
8     9     amol  56.75   20
9    10    anmol  78.66   21

In [62]:
df.drop('class', axis = 1)

   roll     name  marks  age
0     1     anil  56.77   22
1     2     amit  59.77   21
2     3   aniket  76.88   19
3     4  ajinkya  69.66   20
4     5     asha  63.28   20
5     6   ayesha  49.55   20
6     7     amar  65.34   19
7     8    amita  68.33   23
8     9     amol  56.75   20
9    10    anmol  78.66   21

In [63]:
# renaming

In [64]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [65]:
cols = {'roll': 'id', 'marks': 'grade'}

In [66]:
df.rename(columns= cols)

   id     name class  grade  age
0   1     anil    TE  56.77   22
1   2     amit    TE  59.77   21
2   3   aniket    BE  76.88   19
3   4  ajinkya    TE  69.66   20
4   5     asha    TE  63.28   20
5   6   ayesha    BE  49.55   20
6   7     amar    BE  65.34   19
7   8    amita    BE  68.33   23
8   9     amol    TE  56.75   20
9  10    anmol    BE  78.66   21

In [67]:
# rename the index => 1 -> one, 4 -> four

In [68]:
ind = {1: 'one', 4: 'four'}

In [69]:
df.rename(index= ind)

      roll     name class  marks  age
0        1     anil    TE  56.77   22
one      2     amit    TE  59.77   21
2        3   aniket    BE  76.88   19
3        4  ajinkya    TE  69.66   20
four     5     asha    TE  63.28   20
5        6   ayesha    BE  49.55   20
6        7     amar    BE  65.34   19
7        8    amita    BE  68.33   23
8        9     amol    TE  56.75   20
9       10    anmol    BE  78.66   21

In [70]:
# iteration

In [71]:
for i in df:
    print(i)

roll
name
class
marks
age

In [72]:
# using the for loop iterate over the df
# print =>
# column name -> values

In [73]:
for i in df:
    print(f'{i} -> {list(df[i])}')

roll -> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
name -> ['anil', 'amit', 'aniket', 'ajinkya', 'asha', 'ayesha', 'amar', 'amita', 'amol', 'anmol']
class -> ['TE', 'TE', 'BE', 'TE', 'TE', 'BE', 'BE', 'BE', 'TE', 'BE']
marks -> [56.77, 59.77, 76.88, 69.66, 63.28, 49.55, 65.34, 68.33, 56.75, 78.66]
age -> [22, 21, 19, 20, 20, 20, 19, 23, 20, 21]

In [74]:
# sort data

In [75]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [76]:
df.sort_values('marks')

   roll     name class  marks  age
5     6   ayesha    BE  49.55   20
8     9     amol    TE  56.75   20
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
4     5     asha    TE  63.28   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
3     4  ajinkya    TE  69.66   20
2     3   aniket    BE  76.88   19
9    10    anmol    BE  78.66   21

In [77]:
df.sort_values('marks', ascending= False)

   roll     name class  marks  age
9    10    anmol    BE  78.66   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
7     8    amita    BE  68.33   23
6     7     amar    BE  65.34   19
4     5     asha    TE  63.28   20
1     2     amit    TE  59.77   21
0     1     anil    TE  56.77   22
8     9     amol    TE  56.75   20
5     6   ayesha    BE  49.55   20

In [78]:
# sort class and marks columns simulataneosly and check the result

In [79]:
df.sort_values(['class', 'marks'])

   roll     name class  marks  age
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
2     3   aniket    BE  76.88   19
9    10    anmol    BE  78.66   21
8     9     amol    TE  56.75   20
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
4     5     asha    TE  63.28   20
3     4  ajinkya    TE  69.66   20

In [80]:
df.sort_values(['class', 'marks'], ascending= False)

   roll     name class  marks  age
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
1     2     amit    TE  59.77   21
0     1     anil    TE  56.77   22
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21
2     3   aniket    BE  76.88   19
7     8    amita    BE  68.33   23
6     7     amar    BE  65.34   19
5     6   ayesha    BE  49.55   20